# Generated by Django 5.2.4 on 2025-08-02 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_travelentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelentry',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
